#.travis.yml
language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - ls -a && echo ${TRAVIS_BUILD_DIR} && find ${TRAVIS_BUILD_DIR}/dist -exec curl --ftp-create-dirs -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@{DOMAINE_NAME}/${PUBLIC_DIR}

notifications:
  email:
    on_failure: change
    on_success: change
