#.travis.yml
language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

addons:
  ssh_known_hosts: funlab.fr
  apt:
    packages:
    - sshpass

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - sshpass -p ${SFTP_PASSWORD} ssh -v ${SFTP_USER}@funlab.fr 'rm -rfd api.funlab.fr/public/*'
  - sshpass -p ${SFTP_PASSWORD} scp -v -r ${TRAVIS_BUILD_DIR}/dist/projet3-funlab/* ${SFTP_USER}@funlab.fr:api.funlab.fr/public/

  # - ./deploy.sh
  # - cd dist/projet3-funlab/ && find . -type f -exec curl -v -u ${SFTP_USER}:${SFTP_PASSWORD} --ftp-create-dirs -T {} ftp://${DOMAINE_NAME}/${PUBLIC_DIR}/{} \;

notifications:
  email:
    on_failure: change
    on_success: change
