#.travis.yml
language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

addons:
  ssh_known_hosts: funlab.fr
  apt:
    packages:
    - sshpass

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - sshpass -p ${SSH_PASSWORD} ssh -v ${SSH_USER}@funlab.fr 'find prod.funlab.fr/public/* | xargs rm -rfd'
  - sshpass -p ${SSH_PASSWORD} ssh -v ${SSH_USER}@funlab.fr 'rm -rfd prod.funlab.fr/public/*'
  - sshpass -p ${SSH_PASSWORD} scp -v -r ${TRAVIS_BUILD_DIR}/dist/projet3-funlab/* ${SSH_USER}@funlab.fr:prod.funlab.fr/public/

notifications:
  email:
    on_failure: change
    on_success: change
