#.travis.yml
language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - cd dist/projet3-funlab/ && find . -type f -exec curl -v --ftp-create-dirs -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@{DOMAINE_NAME}/${PUBLIC_DIR}

notifications:
  email:
    on_failure: change
    on_success: change
